# fly.toml app configuration file generated for km-messaging-app on 2023-11-09T13:28:28-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "km-messaging-app"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
